version: 2.1
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.2-sdk
    steps:
      - checkout
      - run: 
          name: dotnet --info
          command: dotnet --info
      - run: 
          name: dotnet restore
          command: dotnet restore HumanitarianAssistance.WebApi/HumanitarianAssistance.WebApi.csproj 
      - run: 
          name: dotnet clean
          command: dotnet clean HumanitarianAssistance.WebApi/HumanitarianAssistance.WebApi.csproj 
      - run: 
          name: dotnet build
          command: dotnet build HumanitarianAssistance.WebApi/HumanitarianAssistance.WebApi.csproj 
      - run: 
          name: dotnet run
          command: dotnet run HumanitarianAssistance.WebApi/HumanitarianAssistance.WebApi.csproj 