version: 2.1
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.2-sdk
    steps:
      - checkout
      - run: 
          name: dotnet --info
          command: dotnet --info
      - run: 
          name: dotnet restore
          command: dotnet restore
      - run: 
          name: dotnet clean
          command: dotnet clean
      - run: 
          name: dotnet msbuild
          command: dotnet msbuild
      - run: 
          name: dotnet run
          command: dotnet run