version: 2.1
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.2-sdk
    steps:
      - checkout

      - run: 
          name: install node
          command: "curl -sL https://deb.nodesource.com/setup_10.x | bash -  && apt update  && apt install -y nodejs"
      - run: npm cache clean -f
      - run: npm install -g n
      - run: n stable
      - run: node -v
      - run: npm -v
      - run: npm install -g @angular/cli

      - run: 
          name: dotnet --info
          command: dotnet --info
      - run: 
          name: dotnet restore
          command: dotnet restore HumanitarianAssistance.WebApi/HumanitarianAssistance.WebApi.csproj 
      - run: 
          name: dotnet clean
          command: dotnet clean HumanitarianAssistance.WebApi/HumanitarianAssistance.WebApi.csproj 
      - run: 
          name: dotnet build
          command: dotnet build HumanitarianAssistance.WebApi/HumanitarianAssistance.WebApi.csproj 
      - run: 
          name: dotnet publish
          command: dotnet publish HumanitarianAssistance.WebApi/HumanitarianAssistance.WebApi.csproj -c Release -o release